version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"

  video-service:
    build: ./video-service
    ports:
      - "3001:3001"

  recommender:
    build: ./recommender
    ports: 
      - "3002:3002"